### ISSUE TITLE
第13章 关于正则匹配代理地址的问题

### ISSUE THREAD

**Issue by loveQt** [dongweiming/web_develop#10]
P386页说

> 直接解析 HTML 页面中的代理地址就好了。不需要那么严格的匹配。

然后给出了一个匹配“IP:Port”格式的正则表达式。
我看了 [https://github.com/dongweiming/web_develop/blob/master/chapter13/section1/config.py] 给出的 PROXY_SITES 

```
    'http://cn-proxy.com',
    'http://www.xicidaili.com',
    'http://www.kuaidaili.com/free',
    'http://www.proxylists.net/?HTTP',
    # www.youdaili.net的地址随着日期不断更新
    'http://www.youdaili.net/Daili/http/4565.html',
    'http://www.youdaili.net/Daili/http/4562.html',
    'http://www.kuaidaili.com',
    'http://proxy.mimvp.com',
```

其中  http://cn-proxy.com 已经挂掉不能访问了；
其中 http://www.proxylists.net/?HTTP 和 www.youdaili.net 的代理是文本格式，能够直接按照给出的正则表达式匹配。
剩余的 www.xicidaili.com 、http://www.kuaidaili.com/free 、http://www.kuaidaili.com 给出代理的格式都是表格形式， IP 和端口并不在一起，使用提供的正则匹配不到。一种解决方案是用 bs 匹配 IP 后再获取兄弟节点的端口号：

```
bsObj = BeautifulSoup(html, 'html.parser')
ipList = bsObj.findAll('td', text=re.compile('[0-9]+(?:\.[0-9]+){3}'))
for each in ipList:
    ip = each.get_text()
    port = each.next_sibling.next_sibling.get_text() #因为换行的原因要取两次兄弟节点
    proxy = ip + ':' +port
```

最后一个 http://proxy.mimvp.com 就更扯了…端口一列直接是给出的图片…

综上：
原文的正则只可以匹配以“IP:Port”格式给出的文本，如果网站给出表格形式（IP 和端口在两个<td>标签中）就匹配不到代理地址了。
代码中给出的部分网站不适用直接的正则匹配。

**Comment by loveQt** [comment]
关于表格格式的代理解决方案，因为换行 \n 的存在，匹配兄弟节点适用性不够好（有时是下一个，有时是下下个节点）。
更好的解决办法：
1、清洗 html ，去掉 \n ；
2、借助父节点匹配端口号。

```
bsObj = BeautifulSoup(html, 'html.parser')
ipList = bsObj.findAll('td', text=re.compile('[0-9]+(?:\.[0-9]+){3}'))
for each in ipList:
    ip = each.get_text()
    # port = each.next_sibling.next_sibling.get_text() 因为换行的原因要取两次兄弟节点
    port = each.parent.find('td', text=re.compile('^\d{2,5}$')).get_text() 
    # 测试中遇到5位端口号，遂将{2,4}改为{2,5}
    proxy = ip + ':' +port
```

**Comment by dongweiming** [comment]
额 我开始写这个爬虫的时候大概是3月初，当时找了一些代理网站，大体翻了下，能获取够用的代码列表。具体的没有挨个实验。 半年后代理网站不可用了，用的不对了，我甚无奈。

**Comment by dongweiming** [comment]
但是感谢反馈，这个issue就留着给后人看吧

**Comment by loveQt** [comment]
爬虫就是这样，目标网站随便改改爬虫程序就乱套了…这也是没办法的事。

只不过大概看了一下现在主流的一些代理网站感觉表格的形式比文本要多，才提这个 issue 的。

**Comment by dongweiming** [comment]
@loveQt 嗯 ，我也还是有责任的，最后完稿之前没有再过一遍。当时过的时候，由于代理地址已经存在MongoDB里面了，所以就顺利的跑成功了， 也就忘了验证获取代理地址的源是不是正确的了。

**Comment by dongweiming** [comment]
@loveQt 在勘误中加了说明 https://github.com/dongweiming/web_develop/commit/be7f3aa7d0120d7710f20b2b6e14008131f36c99
