### ISSUE TITLE
第13章 P386 使用fake_useragent.json缓存文件

### ISSUE THREAD

**Issue by loveQt** [dongweiming/web_develop#12]
P386 指出了使用 fake_useragent 时程序会访问被墙的网址获取 UA 缓存，所以如果不挂代理的话会报错：
`urllib.error.URLError: <urlopen error timed out>`
@dongweiming 提供了本地的缓存文件 [web_develop/data/fake_useragent.json](https://github.com/dongweiming/web_develop/blob/master/data/fake_useragent.json)，要将此文件存储到/tmp 文件夹 

在此有一点增加说明和一点勘误：
增加 Windows 平台 tmp 文件夹位置说明：
Windows 平台 tmp 文件夹位置为：C:\Users\username\AppData\Local\Temp
在[fake_useragent/settings.py](https://github.com/hellysmile/fake-useragent/blob/master/fake_useragent/settings.py#L8)中找到源码

```
DB = os.path.join(tempfile.gettempdir(), 'fake_useragent_{version}.json'.format(  # noqa
    version=__version__,
))
```

```
>>> import tempfile
>>> tempfile.gettempdir()
'C:\\Users\\username\\AppData\\Local\\Temp'
```

然而将缓存文件复制到正确的文件夹以后还是不能正常运行，依然没有正确 load 缓存文件而是在访问网站。
检查源码后增加 fake_useragent.json 文件名勘误：

```
__version__ = '0.1.2'

DB = os.path.join(tempfile.gettempdir(), 'fake_useragent_{version}.json'.format(  # noqa
    version=__version__,
))
```

可以看出文件名中缺少了 version
故 [web_develop/data/fake_useragent.json](https://github.com/dongweiming/web_develop/blob/master/data/fake_useragent.json) 文件名应修改为 fake_useragent_0.1.2.json ，否则就算 cp 到正确路径还是不能正常读取缓存。

**Comment by dongweiming** [comment]
@loveQt  项目作者在7月28日在文件上添加了版本的前缀. https://github.com/hellysmile/fake-useragent/commit/c5b2cbc788ebaf94bf2818497a92784c59b4bee1  当时应该指定版本的..

我个人觉得它这样的加了版本修改，实在太隐晦了。

**Comment by dongweiming** [comment]
嗯 再版的时候我一定添加「本书并没有对windows作特别的支持」的说明。未来也没有意愿支持windows..

但是你提示的对。比如mac下：

```
> python -c 'import tempfile; print tempfile.gettempdir()'
/var/folders/gs/l804wd353td_fbnh6rcy2hk40000gn/T
```

**Comment by loveQt** [comment]
嗯，主要是也很少有人会自己去把缓存文件放进文件夹。

人家自然不会考虑我们这特殊国情的…
