### ISSUE TITLE
第三章的数据库建立表 多了个逗号

### ISSUE THREAD

**Issue by casper2dd** [dongweiming/web_develop#18]
## 书中:

CREATE TABLE `PasteFile` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `filename` varchar(5000) NOT NULL,
  `filehash` varchar(128) NOT NULL,
  `filemd5` varchar(128) NOT NULL,
  `uploadtime` datetime NOT NULL,
  `mimetype` varchar(256) NOT NULL,
  `size` int(11) unsigned NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `filehash` (`filehash`),
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
## 正确:

CREATE TABLE `PasteFile` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `filename` varchar(5000) NOT NULL,
  `filehash` varchar(128) NOT NULL,
  `filemd5` varchar(128) NOT NULL,
  `uploadtime` datetime NOT NULL,
  `mimetype` varchar(256) NOT NULL,
  `size` int(11) unsigned NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `filehash` (`filehash`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

**Comment by dongweiming** [comment]
@casper2dd 感谢反馈 其实 https://github.com/dongweiming/web_develop/blob/master/databases/schema.sql#L10 中是正确的。已经添加勘误了 https://github.com/dongweiming/web_develop/blob/master/errata.md

**Comment by dongweiming** [comment]
@casper2dd 是在北京么? 如果你想去pycon北京场，我有优惠券，作为对你勘误的感谢~

**Comment by casper2dd** [comment]
@dongweiming 是的～在北京 就酒仙桥呢 哈哈 pycon北京场  是10月15号么 想去～

**Comment by dongweiming** [comment]
@casper2dd 哈，好，怎么联系你呢？QQ？我加你，然后联系上之后就删掉？

**Comment by dongweiming** [comment]
@casper2dd 给我的邮箱吧邮件也可以 ciici123@gmail.com

**Comment by casper2dd** [comment]
@dongweiming 恩 邮件已发~
