### ISSUE TITLE
第3章LocalProxy的用法有问题

### ISSUE THREAD

**Issue by guyskk** [dongweiming/web_develop#19]
```
def get_current_user():

    users = User.query.all()
    return random.choice(users)

current_user = LocalProxy(get_current_user)
```

https://github.com/dongweiming/web_develop/blob/master/chapter3/section4/app_with_local_proxy.py#L19

这样每次获取current_user的属性都会重新执行一次get_current_user，不能这样用。

**Comment by dongweiming** [comment]
@guyskk 我的例子不就是为了不断刷新页面的时候「Current User」的值会不一样嘛，就是得变啊

**Comment by dongweiming** [comment]
前面的 https://github.com/dongweiming/web_develop/blob/master/chapter3/section4/app.py#L32 也是这个效果嘛

**Comment by guyskk** [comment]
我是说在一个请求中，每次获取current_user的属性都会重新执行一次get_current_user，导致一次请求会多次查询数据库。

也就是说这样的语句

```
name = current_user.name
email = current_user.email
```

会导致查询2次数据库

**Comment by dongweiming** [comment]
对啊 每次 获取 current_user就是要重新执行一遍啊，但是current_user是一个对象，name和email是它的属性，怎么会查询2次呢 你咋实验的？

**Comment by guyskk** [comment]
get_current_user里print一下

**Comment by dongweiming** [comment]
然而我试了下,在[这里](https://github.com/dongweiming/web_develop/blob/master/chapter3/section4/app_with_local_proxy.py#L15)加了print  并没有2次...

**Comment by guyskk** [comment]
??print了几次？一次？

**Comment by guyskk** [comment]
你获取了几个current_user的属性，它就会执行几次

**Comment by dongweiming** [comment]
你好好看看 弄点证据吧

**Comment by KagamiChan** [comment]
这位大哥，你觉得代码有问题，可以把你改过的代码贴出来，再把你的运行结果贴出来，这样交流起来不是更方便吗

**Comment by guyskk** [comment]
OK，我一会把代码贴出来

**Comment by guyskk** [comment]
@KagamiChan 感谢提醒
@dongweiming 我开了新的issue，没贴代码是我的疏忽，请别太介意

**Comment by KagamiChan** [comment]
不客氣，其實 issue 可以由管理者 reopen 的，不用新開
