### ISSUE TITLE
docker pull 镜像好慢😂

### ISSUE THREAD

**Issue by misakar** [dongweiming/web_develop#2]

**Comment by dongweiming** [comment]
@neo1218 你用的是lastest的吧？

试试加速：
1. http://www.imike.me/2016/04/20/Docker%E4%B8%8B%E4%BD%BF%E7%94%A8%E9%95%9C%E5%83%8F%E5%8A%A0%E9%80%9F/
2. https://c.163.com/wiki/index.php?title=DockerHub%E9%95%9C%E5%83%8F%E5%8A%A0%E9%80%9F

**Comment by misakar** [comment]
好，我试试，🙏

**Comment by misakar** [comment]
可以啦，谢谢，！
