### ISSUE TITLE
[勘误]第三章 81 页 UPLOAD_FOLDER

### ISSUE THREAD

**Issue by lxian** [dongweiming/web_develop#21]
书中为 UPLOAD_FOLDER = '/tmp/permdir' 但我需要将其改为 'tmp/permdir' 才能令 `os.path.join` 生成正确的path

**Comment by dongweiming** [comment]
额 你用的不是ubuntu吧？mac？Ubuntu下可以用/tmp/permdir呀

**Comment by dongweiming** [comment]
@lxian

**Comment by lxian** [comment]
@dongweiming 是ubuntu

```
In [1]: import os

In [2]: os.path.join('/some/', '/path')
Out[2]: '/path'

In [3]: os.path.join('/some/', 'path')
Out[3]: '/some/path'
```

**Comment by dongweiming** [comment]
@lxian UPLOAD_FOLDER这个变量在 [config.py](https://github.com/dongweiming/web_develop/blob/master/chapter3/section5/config.py#L4)里面，是可以被重载了。在代码[utils.py](https://github.com/dongweiming/web_develop/blob/master/chapter3/section5/utils.py#L38)中使用 是为了更灵活的指定文件目录。

/tmp/permdir也是正确的用法，就是让他在join时候忽略前面的路径，你要是就愿意放在项目目录下就写成tmp/permdir。但这不是错误。

**Comment by dongweiming** [comment]
这种语法常识我是懂的，只是在书中没有具体说明

**Comment by WeJie** [comment]
使用 Mac 需要将
```
UPLOAD_FOLDER = '/temp/permdir'
```
改为
```
UPLOAD_FOLDER = './temp/permdir'
```
否则提示
```
IOError: [Errno 2] No such file or directory: u'/temp/permdir/83e901863a764b6c94048be7fb0bf793.jpeg'
```
