### ISSUE TITLE
[勘误] 85 页 with open(rst.path) as f: 应为 with open(rst.path, 'rb') as f:

### ISSUE THREAD

**Issue by lxian** [dongweiming/web_develop#22]
`with open(rst.path) as f:` 应为 `with open(rst.path, 'rb') as f:` 

代码里是正确的，但是我是跟书做的，一开始出错了还挺困惑的

**Comment by dongweiming** [comment]
@lxian 你在北京么? 要不参加明天的pycon北京场？ 我可以送票。抱歉最近太忙 没时间来勘误

**Comment by dongweiming** [comment]
额 你是用的Python 3吧.. 

代码是因为 https://github.com/dongweiming/web_develop/issues/6 而兼容的

事实上写的时候 我并没想兼容Python 3

**Comment by lxian** [comment]
@dongweiming 不在北京，多谢啦。恩我用的Python 3.5
