### ISSUE TITLE
第三章 section 5 PasteFile.create_by_old_paste 的用意

### ISSUE THREAD

**Issue by lxian** [dongweiming/web_develop#23]
1. 不太明白这个func 是做什么的，感觉上就是把旧的 object 复制了一遍。
2. 在 `app.preview` 里面为什么会用到这个 func ?

谢谢

**Comment by dongweiming** [comment]
@lxian 技术讨论请到 python-cn.org.....

**Comment by dongweiming** [comment]
@lxian 抱歉，这个地方用错了。豆瓣内部的版本比这个要复杂，有误删除的备份策略，原来是只删除数据库的对应条目，也就是再使用 get_by_filehash的时候就没有记录了，但是文件没有删除，对应的短连接也保存着，使用 create_by_old_paste 可以恢复。我在重构的时候去掉了这部分，但是在preview中错误的用了原来的可恢复逻辑。一会我勘个误 感谢

**Comment by dongweiming** [comment]
@lxian 详情看这里 http://python-cn.org/topic/21/pastefile-create_by_old_paste%E7%9A%84%E7%94%A8%E6%84%8F%E6%98%AF%E4%BB%80%E4%B9%88

**Comment by lxian** [comment]
@dongweiming 谢啦 我之前没注意到python-cn.org 上面有这个版面
