### ISSUE TITLE
P81  在python3下from werkzeug import SharedDataMiddleware出错

### ISSUE THREAD

**Issue by sunshine-sjd** [dongweiming/web_develop#24]
python3的环境导入报错，改为from werkzeug.wsgi import SharedDataMiddleware可以。
这个是否跟python版本有关？
谢谢

**Comment by dongweiming** [comment]
@sunshine-sjd 本书的内容其实没有在Python 3实验过。我刚才创建了一个3.5.2的，是可以的：

```
❯ source venv3/bin/activate
❯ pip install werkzeug
Collecting werkzeug
  Using cached Werkzeug-0.11.11-py2.py3-none-any.whl
Installing collected packages: werkzeug
Successfully installed werkzeug-0.11.11

~/test m1*
❯ python
Python 3.5.2 (default, Aug 16 2016, 05:35:40) 
[GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from werkzeug.wsgi import SharedDataMiddleware
>>> 
```

按说和Python版本应该是没关系的

**Comment by sunshine-sjd** [comment]
@dongweiming  恩恩，没关系，是我用的pycharm误导我了，用from werkzeug import SharedDataMiddleware会提示unresolved reference SharedDataMiddleware，其实是可以导入的，原因貌似是因为在werkzeug下的**init**.py已经包含werkzeug.wsgi模块，所以可以直接from werkzeug而不用from werkzeug.wsgi导入
