### ISSUE TITLE
vagrant up出现错误

### ISSUE THREAD

**Issue by tuihongshiyu** [dongweiming/web_develop#25]
PS C:\Users\dell\Documents\GitHub\web_develop-master> vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
There are errors in the configuration of this machine. Please fix
the following errors and try again:

SSH:
- `private_key_path` file must exist: ~/.ssh/id_rsa

File provisioner:
- File upload source file C:/Users/dell/.ssh/id_rsa.pub must exist

该如何解决

**Comment by zijuanhuakai** [comment]
打开git bash,在~目录下输入ssh-keygen命令生成这两个文件。

**Comment by dongweiming** [comment]
@tuihongshiyu @zijuanhuakai 说得对，书中有介绍，虽然我没在windows下试过

**Comment by tuihongshiyu** [comment]
@zijuanhuakai @dongweiming 非常感谢
dell@Shanshen MINGW64 ~/web_develop (master)
$ vagrant reload
==> default: Attempting graceful shutdown of VM...
    default: Guest communication could not be established! This is usually because
    default: SSH is not running, the authentication information was changed,
    default: or some other networking issue. Vagrant will force halt, if
    default: capable.
==> default: Forcing shutdown of VM...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 9000 (guest) => 9000 (host) (adapter 1)
    default: 3141 (guest) => 3141 (host) (adapter 1)
    default: 5000 (guest) => 5000 (host) (adapter 1)
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: ubuntu
    default: SSH auth method: password
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.
然后碰到启动失败，虽然另两个isuue里都有提到，但是似乎虚拟机没有启动成功

**Comment by tuihongshiyu** [comment]
另，在Docker Quickstart Terminal 中出现

Creating Machine default...
Creating CA: C:\Users\dell.docker\machine\certs\ca.pem
Creating client certificate: C:\Users\dell.docker\machine\certs\cert.pem
Creating VirtualBox VM...
Creating SSH key...
Starting VirtualBox VM...
Starting VM...

的情况

**Comment by dongweiming** [comment]
@tuihongshiyu 再版的时候我一定要申明不支持windows系统。建议你换个平台，对你是有好处的

**Comment by czly** [comment]
哪个个人电脑用的不是windows?你这都没法使，书有啥用？

**Comment by dongweiming** [comment]
@czly 要不要学linux 要不然去退书，别在这丢人
