### ISSUE TITLE
求教开发平台习惯等

### ISSUE THREAD

**Issue by neconano** [dongweiming/web_develop#26]
大神你好，刚买了您的书，目前只看到hello wold阶段

没在书里面找到开发时候使用的开发平台是什么

比如您平时用什么环境，什么工具写代码，如何提高开发效率

**Comment by dongweiming** [comment]
Mac emacs

**Comment by dongweiming** [comment]
这种问题非勘误和反馈 请按书中的要求去 python-cn.org发帖讨论。而且这种问题还是你要有自己的方式，我无力回答
