### ISSUE TITLE
好想骂人

### ISSUE THREAD

**Issue by czly** [dongweiming/web_develop#27]
我下载了最新版的 vagrant 和virtualbox,按默认安装了，之后呢？怎么安ubuntu? 怎么安装配置vagrant，请给一个详细pdf补充上

**Comment by xzenge** [comment]
花几秒钟百度&Google就明白的东西，何必在这秀下限呢。况且作者的书中也写的很清楚了，照着做一般就不会出什么问题。
Vagrant简介和安装配置：http://rmingwang.com/vagrant-commands-and-config.html
Vgrant使用入门：https://github.com/astaxie/Go-best-practice/blob/master/ebook/zh/01.3.md

**Comment by czly** [comment]
F:\web_develop>vagrant box add Vagrantfile
==> box: Box file was not detected as metadata. Adding it directly...
A name is required when adding a box file directly. Please pass
the `--name` parameter to `vagrant box add`. See
`vagrant box add -h` for more help.

F:\web_develop>

这个怎么安装？书里没有写清啊
