### ISSUE TITLE
请问书中提到的装ubuntu，box在哪下载？

### ISSUE THREAD

**Issue by czly** [dongweiming/web_develop#28]
请问书中提到的装ubuntu，box在哪下载？

**Comment by misakar** [comment]
谷歌 "vagrant ubuntu box"

https://atlas.hashicorp.com/ubuntu/boxes/trusty64

**Comment by czly** [comment]
我依次打了如下命令
vagrant init ubuntu/trusty64
 vagrant up --provider virtualbox

提示错误
F:\web_develop>vagrant init ubuntu/trusty64
`Vagrantfile` already exists in this directory. Remove it before
running `vagrant init`.

F:\web_develop>vagrant up --provider virtualbox
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'dongweiming/web_develop' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
The box 'dongweiming/web_develop' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Atlas, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://atlas.hashicorp.com/dongweiming/web_develop"]
Error: Could not resolve host: atlas.hashicorp.com
