### ISSUE TITLE
请问书中提到的装ubuntu，第9页的box在哪下载？

### ISSUE THREAD

**Issue by czly** [dongweiming/web_develop#29]
请问书中提到的装ubuntu，box在哪下载？

**Comment by misakar** [comment]
#28

**Comment by czly** [comment]
我依次打了如下命令
vagrant init ubuntu/trusty64
vagrant up --provider virtualbox

提示错误
F:\web_develop>vagrant init ubuntu/trusty64
Vagrantfile already exists in this directory. Remove it before
running vagrant init.

F:\web_develop>vagrant up --provider virtualbox
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'dongweiming/web_develop' could not be found. Attempting to find and install...
default: Box Provider: virtualbox
default: Box Version: >= 0
The box 'dongweiming/web_develop' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Atlas, please verify you're logged in via
vagrant login. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://atlas.hashicorp.com/dongweiming/web_develop"]
Error: Could not resolve host: atlas.hashicorp.com

**Comment by czly** [comment]
我用的win10 
用vagrant up之后漫长等待中

**Comment by czly** [comment]
win10 
ssh-keygen在哪执行啊？

**Comment by czly** [comment]
win10可以用你这书吗？

**Comment by czly** [comment]
如不不支持，请在图书简介里写上，不支持win10

**Comment by misakar** [comment]
#25

**Comment by czly** [comment]
ssh-keygen 输入文件名必须为
id_rsa吗？

**Comment by czly** [comment]
SSH:
- `private_key_path` file must exist: ~/.ssh/id_rsa

File provisioner:
- File upload source file C:/Users/dell/.ssh/id_rsa.pub must exist
  我在C:\Users\dell 目录下建.ssh目录，提示我必须键入文件名，我保存不了目录名怎么办？

**Comment by czly** [comment]
# coding: utf-8

Vagrant.configure(2) do |config|
  config.vm.box = "dongweiming/web_develop"
  config.vm.hostname = "WEB"
  config.vm.network :forwarded_port, guest: 9000, host: 9000
  config.vm.network :forwarded_port, guest: 3141, host: 3141
  config.vm.network :forwarded_port, guest: 5000, host: 5000

# config.ssh.username = 'ubuntu'

# config.ssh.password = 'ubuntu'

# config.ssh.insert_key = false

# config.ssh.private_key_path = ["~/.ssh/id_rsa"]

 # config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  # config.vm.network "public_network", bridge: "en0: Wi-Fi (AirPort)"
  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--name", "web_dev", "--memory", "1536"]
  end
end

win10系统，我将ssh相关注释掉

F:\web_develop>vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'dongweiming/web_develop'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'dongweiming/web_develop' is up to date...
==> default: Setting the name of the VM: web_develop_default_1476779394470_36138
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 9000 (guest) => 9000 (host) (adapter 1)
    default: 3141 (guest) => 3141 (host) (adapter 1)
    default: 5000 (guest) => 5000 (host) (adapter 1)
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...

F:\web_develop>==> default: Waiting for cleanup before exiting...
Vagrant exited after cleanup due to external interrupt.

**Comment by czly** [comment]
# coding: utf-8

Vagrant.configure(2) do |config|
  config.vm.box = "dongweiming/web_develop"
  config.vm.hostname = "WEB"
  config.vm.network :forwarded_port, guest: 9000, host: 9000
  config.vm.network :forwarded_port, guest: 3141, host: 3141
  config.vm.network :forwarded_port, guest: 5000, host: 5000
  config.ssh.username = 'ubuntu'
  config.ssh.password = 'ubuntu'

# config.ssh.insert_key = false

# config.ssh.private_key_path = ["~/.ssh/id_rsa"]

 # config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  # config.vm.network "public_network", bridge: "en0: Wi-Fi (AirPort)"
  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--name", "web_dev", "--memory", "1536"]
  end
end

F:\web_develop>vagrant provision

F:\web_develop>vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'dongweiming/web_develop' is up to date...
==> default: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> default: flag to force provisioning. Provisioners marked to run always will still run.

F:\web_develop>

**Comment by czly** [comment]
F:\web_develop>vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'dongweiming/web_develop' is up to date...
==> default: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> default: flag to force provisioning. Provisioners marked to run always will still run.

我把ssh配置好了，出现这个错误

**Comment by czly** [comment]
==> default: Importing base box 'dongweiming/web_develop'...
Progress: 10%There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["import", "C:/Users/dell/.vagrant.d/boxes/dongweiming-VAGRANTSLASH-web_develop/0.5/virtualbox/box.ovf", "--vsys", "0", "--vmname", "web_dev_1476780941166_37258", "--vsys", "0", "--unit", "8", "--disk", "C:\Users\dell\VirtualBox VMs\web_dev_1476780941166_37258\box-disk1_1.vmdk", "--vsys", "0", "--unit", "9", "--disk", "C:\Users\dell\VirtualBox VMs\web_dev_1476780941166_37258\box-disk2_1.vmdk"]

Stderr: 0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
Interpreting C:\Users\dell.vagrant.d\boxes\dongweiming-VAGRANTSLASH-web_develop\0.5\virtualbox\box.ovf...
OK.
0%...10%...
Progress state: VBOX_E_FILE_ERROR
VBoxManage.exe: error: Appliance import failed
VBoxManage.exe: error: Could not create the imported medium 'C:\Users\dell\VirtualBox VMs\web_dev_1476780941166_37258\box-disk1_1.vmdk'.
VBoxManage.exe: error: VMDK: cannot write allocated data block in 'C:\Users\dell\VirtualBox VMs\web_dev_1476780941166_37258\box-disk1_1.vmdk' (VERR_DISK_FULL)
VBoxManage.exe: error: Details: code VBOX_E_FILE_ERROR (0x80bb0004), component ApplianceWrap, interface IAppliance
VBoxManage.exe: error: Context: "enum RTEXITCODE __cdecl handleImportAppliance(struct HandlerArg *)" at line 886 of file VBoxManageAppliance.cpp
