### ISSUE TITLE
win10用git bash 执行 $ vagrant up报错

### ISSUE THREAD

**Issue by czly** [dongweiming/web_develop#31]
Progress state: VBOX_E_FILE_ERROR
VBoxManage.exe: error: Appliance import failed
VBoxManage.exe: error: Could not create the imported medium 'C:\Users\dell\Virtu                                                                                                                                                                                               alBox VMs\web_dev_1476789817454_26795\box-disk1_1.vmdk'.
VBoxManage.exe: error: VMDK: cannot write allocated data block in 'C:\Users\dell                                                                                                                                                                                               \VirtualBox VMs\web_dev_1476789817454_26795\box-disk1_1.vmdk' (VERR_DISK_FULL)
VBoxManage.exe: error: Details: code VBOX_E_FILE_ERROR (0x80bb0004), component A                                                                                                                                                                                               pplianceWrap, interface IAppliance
VBoxManage.exe: error: Context: "enum RTEXITCODE __cdecl handleImportAppliance(s                                                                                                                                                                                               truct HandlerArg *)" at line 886 of file VBoxManageAppliance.cpp

怎么解决？

**Comment by KagamiChan** [comment]
`VERR_DISK_FULL` 已经告诉你了，磁盘空间不足
看了你一下午的问题，建议还是用 linux 吧，搞 python web 开发最终还是会用 *nix 的，就算你本地开发折腾了半天用了 windows，最后不还是得部署在 linux 上运行
不想电脑上安装双系统的话，用虚拟机装一个也行啊

**Comment by dongweiming** [comment]
@czly 要不然去学linux 要不然去把书退了

**Comment by dongweiming** [comment]
还有 请不要浪费issue

**Comment by czly** [comment]
我在这里问问题没有一点不对，我只是是一个消费者，用的电脑的windows,网站服务器用的centos，但是网站服务器空间有限，扩容需要好多费用，所以只能在win10里按您书上写的装虚拟环境

现在遇到的问题是 按您第10页写的内容 操作完
在
C:\Users\dell\VirtualBox VMs\web_dev 生成了web_dev.vbox，直接双击它，启动了虚拟环境

但是vagrant provision 和 vagrant ssh没法执行了

C:\Users\dell\VirtualBox VMs\web_dev>vagrant provision
A Vagrant environment or target machine is required to run this
command. Run `vagrant init` to create a new Vagrant environment. Or,
get an ID of a target machine from `vagrant global-status` to run
this command on. A final option is to change to a directory with a
Vagrantfile and to try again.

C:\Users\dell\VirtualBox VMs\web_dev>vagrant ssh
A Vagrant environment or target machine is required to run this
command. Run `vagrant init` to create a new Vagrant environment. Or,
get an ID of a target machine from `vagrant global-status` to run
this command on. A final option is to change to a directory with a
Vagrantfile and to try again.

执行的时候会报这个错误

**Comment by czly** [comment]
C:\Users\dell\VirtualBox VMs\web_dev>vagrant provision
==> default: VM not created. Moving on...
