### ISSUE TITLE
数据库部分代码瑕疵

### ISSUE THREAD

**Issue by tttimit** [dongweiming/web_develop#32]
第三章 Flask Web 开发中P66-P67页所示的例子中，缺少了一句关键的代码
`users.create()`
按照原书中的代码，执行后会报 r.Users 表不存在的问题。
其实在P67页“分析一下这个例子中“中第一条就有了，但是代码部分缺少了创建表的那一句

**Comment by dongweiming** [comment]
@ttimit 感谢提醒 代码中是[有的](https://github.com/dongweiming/web_develop/blob/master/chapter3/section3/exp_sql.py#L18)但是书中没有出现

**Comment by dongweiming** [comment]
@tttimit 已在 https://github.com/dongweiming/web_develop/blob/master/errata.md#代码错误 添加这个问题为第四个错误
