### ISSUE TITLE
vagrant vbox 添加vbox文件怎么写？

### ISSUE THREAD

**Issue by czly** [dongweiming/web_develop#33]
请问我想把这个文件添加进来，怎么写命令？
C:\Users\dell\VirtualBox VMs\web_dev\web_dev.vbox
vagrant vbox add

**Comment by czly** [comment]
我这样写会报错
C:\Users\dell\VirtualBox VMs\web_dev>vagrant box add web_dev web_dev.vbox
==> box: Box file was not detected as metadata. Adding it directly...
==> box: Adding box 'web_dev' (v0) for provider:
    box: Unpacking necessary files from: file://C:/Users/dell/VirtualBox%20VMs/web_dev/web_dev.vbox
    box: Progress: 100% (Rate: 6791/s, Estimated time remaining: 0:00:01)
The box failed to unpackage properly. Please verify that the box
file you're trying to add is not corrupted and try again. The
output from attempting to unpackage (if any):

bsdtar.EXE: Error opening archive: Unrecognized archive format

C:\Users\dell\VirtualBox VMs\web_dev>

**Comment by dongweiming** [comment]
@czly 我写的是Python Web开发 不做基础知识普及，我也没空教你，请善用google。

# 还有请不要占用issue资源问这种问题

**Comment by czly** [comment]
我艹你妈个傻b，你小学语文毕业了吗？你不配写书 傻b
