### ISSUE TITLE
mac下 安装docker.img 之后初始化一直卡 不能成功问题

### ISSUE THREAD

**Issue by fremindmm** [dongweiming/web_develop#35]
Running pre-create checks...
(default) Default Boot2Docker ISO is out-of-date, downloading the latest release...
(default) Latest release for github.com/boot2docker/boot2docker is v1.12.2
(default) Downloading /Users/benben/.docker/machine/cache/boot2docker.iso from https://github.com/boot2docker/boot2docker/releases/download/v1.12.2/boot2docker.iso...

^C

解决办法：
使用命令：docker-machine create -d virtualbox --virtualbox-boot2docker-url=https://github.com/boot2docker/boot2docker/releases/download/v1.12.2/boot2docker.iso default

**Comment by dongweiming** [comment]
@fremindmm 这是你的Boot2Docker版本太低的问题 和本书没啥关系吧

**Comment by fremindmm** [comment]
但是如果按照 书上步骤操作 是会遇到这个问题的 所以提出来了

**Comment by dongweiming** [comment]
@fremindmm 感谢~
