### ISSUE TITLE
勘误

### ISSUE THREAD

**Issue by lambdaplus** [dongweiming/web_develop#38]
书中，第三章第5节中 models.py 里的 create_by_upload_file函数，
with open(rst.path) as f:
少了打开方式

github上是
with open (rst.path, 'rb') as f:

**Comment by dongweiming** [comment]
@lambdaplus 你用的Python 3吧？https://github.com/dongweiming/web_develop/issues/22

**Comment by dongweiming** [comment]
@lambdaplus 你用的Python 3吧？https://github.com/dongweiming/web_develop/issues/22

**Comment by lambdaplus** [comment]
谢谢
