### ISSUE TITLE
第3章 PasteFile类中使用 @property

### ISSUE THREAD

**Issue by xiaomiba0904** [dongweiming/web_develop#39]
您好请问用
`@property
def path(self):
    return get_file_path(self.filehash)`
跟直接在**init**中写
   self.path = get_file_path(self.filehash)
这2个用法有什么区别，第一个优势是什么，您为什么用第一种？谢谢

**Comment by dongweiming** [comment]
@xiaomiba0904  这个问题挺好。对这个例子来说，这2种用法的效果是一样的，但是我**一般不会在初始化的时候添加不必要的、需要执行的语句，而是在需要的时候才去执行**。这算是一种我的编程习惯吧，因为可能大部分的初始化 并不需要知道self.path是什么，如果放在__init__里面，那么就是无差别的都要执行一次，然而实际上用不到

**Comment by xiaomiba0904** [comment]
谢谢解惑
