### ISSUE TITLE
[勘误] P360 疑似表述错误

### ISSUE THREAD

**Issue by ming2281** [dongweiming/web_develop#41]
位置: 12章--了解 Linux 服务器运行情况--free

上下文: 纵轴上还有一行 "-/+ buffers/cache"......其中` "-buffers/cache" `表示已用内存...... `"- buffers/cache" ` 表示可用内存......

我的疑惑: 加粗的两个部分( ` -buffers/cache ` ), 是指的同一个东西吗( 按照语境来看, 应该指示两个不同的东西 )

我的猜测: 根据上下文, 我觉得可能是想表述` + buffers/cache`

**Comment by dongweiming** [comment]
@hezhiming 抱歉之前手头一直没有书来确认。

确实是个错误。[已勘误](https://github.com/dongweiming/web_develop/commit/d2d92dd5cde3ceb48738708cf84fe48ee0113b50)，感谢
