### ISSUE TITLE
书中有一处用词需更正

### ISSUE THREAD

**Issue by ethan-funny** [dongweiming/web_develop#45]
第 14 章 Python 进阶，collections 模块。

Counter: 一个方便、快速计算的计时器工具。这里的**计时器**应该改为**计数器**。

**Comment by dongweiming** [comment]
@ethan-funny 感谢反馈。已更正： https://github.com/dongweiming/web_develop/commit/644d847ae472fdc38e33eab76f49d542819736a3

**Comment by ethan-funny** [comment]
@dongweiming 好的。
