### ISSUE TITLE
勘误 文本错误

### ISSUE THREAD

**Issue by Abirdcfly** [dongweiming/web_develop#5]
看起来第12章几个µs和ns被印刷成了 '框s' 。
P338上面的代码

```
In      : %timeit range(1000)
100000 loops, best of 3: 9.2 µs per loop
```

P341中间的代码

```
In   : %time range(10)
CPU times: user 0 ns, sys: 4 ns, total: 4 ns
Wall time: 8 µs
Out: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
```

**Comment by dongweiming** [comment]
@Abirdcfly 感谢反馈，已修正 https://github.com/dongweiming/web_develop/commit/5d448526ea44975afad14c858c035f310dc3fb72

**Comment by silencewwt** [comment]
第六章也有同样的问题
P177中间偏下

```
In : %timeit -n 10000 get_hour_data2(1)
10000 loops, best of 3: 311 □s per loop
```

**Comment by dongweiming** [comment]
@Silence-WWT 感谢反馈，已修复 https://github.com/dongweiming/web_develop/commit/ae2cf98120503319928ef8c0600fae66ba0a08ac

**Comment by Reo-LEI** [comment]
第六章 P146 第二行： server unix 前面的 # 是不是多余的？
`server 127.0.0.1:8002;`
`# server unix:/tmp/gunicorn.sock;`

第六章 p148 “通过Gunicorn启动flask应用”下原文为：
“...为了演示，这里只启动8000端口的Gunicorn实例"
但实际代码启动了9000端口，原文如下：
`> gunicorn -w 3 chapter6.section1.app:app -b :9000`

**Comment by dongweiming** [comment]
@Reo-LEI P146的井号只是为了说明有这个用法。第二个端口确实有问题 已改 https://github.com/dongweiming/web_develop/commit/1d940bf236718fb6a187bc456b4f5be67b29eab7

**Comment by yyt030** [comment]
想问下，第六章176页，mongodb实战经验，采用组合方式，把一个小时日志放到一个文档中下面的语句是不是有问题？
建议作者单独列下书中的勘误，也让我们自己手工修改下或者再版的时候纠正下。呵呵

**Comment by ryanli1994** [comment]
p104
权限有误，可读应该是（4），可执行应该是（1）

**Comment by sunshine-sjd** [comment]
p31
最后两行 

> export YOURAPPALICATION_SETTINGS='settings.py'
> app.config.from_envvar('SETTINGS') 

app.config.from_envvar('SETTINGS') 里的'SETTINGS'是不是应该改为 'YOURAPPLICATION_SETTINGS'?

**Comment by MrCJJW** [comment]
第3章P58 mako的模板继承
`<!DOCTYPE html>
<html lang="en">
<head>
    <%block name="head">
        <meta charset="UTF-8">
        <title>${ title() } - My Webpage</title>
    </%block>
</head>
<body>
    <div id="content">
        <%block name="content"/>
    </div>
    <div id="footer">
        <%block name="footer"/>
    </div>
</body>
</html>

<%def name='title()'></%def>`
`<title>${ title() } - My Webpage</title>`是否改为`<title>${ self.title() } - My Webpage</title>`。
如果没加self，子模板继承后就算重写title()函数，使用parernt.head()时使用的还是原来的title函数，但此处例子是希望子模板使用改写后的title函数

**Comment by MrCJJW** [comment]
第3章P58 mako的模板继承
```
<!DOCTYPE html>
<html lang="en">
<head>
    <%block name="head">
        <meta charset="UTF-8">
        <title>${ title() } - My Webpage</title>
    </%block>
</head>
<body>
    <div id="content">
        <%block name="content"/>
    </div>
    <div id="footer">
        <%block name="footer"/>
    </div>
</body>
</html>

<%def _name='title()'></%def>
```
```<title>${ title() } - My Webpage</title>```
是否改为
```<title>${ self.title() } - My Webpage</title>```。
如果没加self，子模板继承后就算重写title()函数，使用parernt.head()时使用的还是原来的title函数，但此处例子是希望子模板改写title函数使相关内容发生改变

**Comment by dongweiming** [comment]
@yyt030 @sunshine-sjd 提问题前请先仔细看序言和项目README.这种问题我只回答一遍 https://github.com/dongweiming/web_develop/blob/master/errata.md

**Comment by ryanli1994** [comment]
@dongweiming 权限问题呢？

**Comment by dongweiming** [comment]
@ryanli1994 感谢，是我按着记忆直接写了，也没验证。 已改正 https://github.com/dongweiming/web_develop/commit/f9a6b608207dcf23c2241f1ed1997ae5ecd12a11

**Comment by dongweiming** [comment]
这个issue就到此吧，新的问题请发新的issue

**Comment by dongweiming** [comment]
@ryanli1994 @sunshine-sjd @Reo-LEI @Abirdcfly 请问你们有人在北京么？如果想去pycon北京场，我可以送票作为勘误的感谢 😄

**Comment by sunshine-sjd** [comment]
@dongweiming 不在北京，在杭州呢...

**Comment by ryanli1994** [comment]
@dongweiming 在上海...

**Comment by dongweiming** [comment]
@ryanli1994 @sunshine-sjd 好~ 那就等其他机会吧

**Comment by Abirdcfly** [comment]
@dongweiming 非常感谢，但是时间上赶不上/(ㄒoㄒ)/~~
