### ISSUE TITLE
SSL read: error:00000000:lib(0):func(0):reason(0), errno 104

### ISSUE THREAD

**Issue by Willib** [dongweiming/web_develop#50]
Mac上用parallels搭建的虚拟机来跑得，装的系统为Ubuntu 16.04 LTS。
跟着书中的安装步骤到了 > vagrant up 时就报错了加了sudo后还是一样，求帮忙看一下！
xxx@Parallels-Virtual-Platform:~/Downloads/web_develop$ sudo vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'dongweiming/web_develop' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Loading metadata for box 'dongweiming/web_develop'
    default: URL: https://atlas.hashicorp.com/dongweiming/web_develop
==> default: Adding box 'dongweiming/web_develop' (v0.5) for provider: virtualbox
    default: Downloading: https://atlas.hashicorp.com/dongweiming/boxes/web_develop/versions/0.5/providers/virtualbox.box
==> default: Box download is resuming from prior download progress
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

SSL read: error:00000000:lib(0):func(0):reason(0), errno 104

**Comment by Willib** [comment]
@dongweiming 在这里卡着很难受，看到后还请指点一下哈。

**Comment by Willib** [comment]
我把vagrantfile文件中的config.ssh.username和...password改为了我当前登陆的用户名和密码后，报的就是另一个错了，哭死。。。
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'dongweiming/web_develop' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Loading metadata for box 'dongweiming/web_develop'
    default: URL: https://atlas.hashicorp.com/dongweiming/web_develop
==> default: Adding box 'dongweiming/web_develop' (v0.5) for provider: virtualbox
    default: Downloading: https://atlas.hashicorp.com/dongweiming/boxes/web_develop/versions/0.5/providers/virtualbox.box
==> default: Box download is resuming from prior download progress
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

Unknown SSL protocol error in connection to atlas.hashicorp.com:443

**Comment by Willib** [comment]
昨晚花了一晚上时间从百度网盘下载了virtualBox，坑爹的百度网盘贼慢，然后通过>vagrant box add dongweiming/web_develop virtualbox.box 加上去，提示信息为成功：
==> box: Box file was not detected as metadata. Adding it directly...
==> box: Adding box 'dongweiming/web_develop' (v0) for provider: 
    box: Unpacking necessary files from: file:///home/dove/Downloads/web_develop/virtualbox.box
==> box: Successfully added box 'dongweiming/web_develop' (v0) for 'virtualbox'!

然后当我用> vagrant up启动时又出现问题了，这个该怎么破啊，😭😭
==> default: Importing base box 'dongweiming/web_develop'...
==> default: Matching MAC address for NAT networking...
==> default: Setting the name of the VM: web_develop_default_1487381782192_42651
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 9000 (guest) => 9000 (host) (adapter 1)
    default: 3141 (guest) => 3141 (host) (adapter 1)
    default: 5000 (guest) => 5000 (host) (adapter 1)
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "e6fb471e-436b-4573-88e0-7b47fb8c4c38", "--type", "headless"]

Stderr: VBoxManage: error: The virtual machine 'web_dev' has terminated unexpectedly during startup with exit code 1 (0x1)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MachineWrap, interface IMachine

**Comment by Willib** [comment]
好吧，后来发现应该下载virtualbox amd64版本的，而我下成了i386，然后再运行的时候发现提示错误，Error VT-x not available for Vagrant machine inside Virtualbox
到这个问题的时候，最后才发现vagrant和virtualbox不能安装在虚拟机中，而应该安装在宿主机里面才行。对于小白来说多么蛋疼的领悟。然后直接在OS X上安装完事儿。o(╯□╰)o

**Comment by dongweiming** [comment]
ok
