### ISSUE TITLE
询问作者大大

### ISSUE THREAD

**Issue by thomaszdxsn** [dongweiming/web_develop#51]
第二章搭建开发环境，使用命令 vagrant up下载box总是出错，昨晚试了好多遍还是不行，原因都是超时。

今天再试着下载，结果报这个错：

URL: ["https://atlas.hashicorp.com/dongweiming/web_develop"]
Error: Couldn't resolve host 'atlas.hashicorp.com'

然后去网上搜索，找到作者大大在豆瓣的回复，看到一个百度云的资源，正在下载中。

请问这个.box文件下载后怎么使用
请问这个box只适用与ubuntu吗，我现在是mac。如果要用这个box必须先装一个ubuntu的虚拟机吗

**Comment by solarhell** [comment]
1:用法可以参考这里 https://solarhell.com/post/2016/04/homestead
2:与你的系统无关 就是一个封装好的镜像

**Comment by thomaszdxsn** [comment]
多谢，我已经安装好了vagrant，并且能够通过ssh进入ubuntu。

我还有个问题就是之后的docker安装，书上的内容我不是很懂。我是mac下载Mac版的docker，还是需要和虚拟机ubuntu匹配的docker，如果是虚拟机的docker要怎么下载。。

如果是mac的docker后面那句命令我看不懂，>docker pull dongweiming/web_develop:dev 。docker的terminal怎么知道镜像在哪里，好像并没有提供绝对路径

**Comment by solarhell** [comment]
书上应该是在讲两种搭建开发环境的方法。
方法1就是vagrant，方法2是docker，2种方法都是母鸡安装，也就是在macOS安装。
默认有一个路径，macOS的话是这个目录`~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/...`

**Comment by dongweiming** [comment]
@thomaszdxsn 有问题还是多google吧

**Comment by dongweiming** [comment]
非常感谢 @solarhell 的解释
