### ISSUE TITLE
about Docker image

### ISSUE THREAD

**Issue by kangni** [dongweiming/web_develop#55]
刚才pull了latest，足足6G，可怜我的120G硬盘😭

可以麻烦小明老师优化下吗？🐱

**Comment by dongweiming** [comment]
嗯，里面包含了大部分书中内容的库文件，docker镜像文件设计的就是很大。我现在都不敢再更新了~

你可以考虑用latest的快速过一遍，然后用dev的，这样跟着书试验过来会学得更多。

btw，我好奇你电脑里面有什么占空间的内容.. 🤔
