### ISSUE TITLE
85页，create_by_upload_file方法上传同名文件报错

### ISSUE THREAD

**Issue by ShoneKey** [dongweiming/web_develop#56]
> 原方法：
> 
**> def create_by_upload_file(cls, uploaded_file):
>         rst = cls(uploaded_file.filename, uploaded_file.mimetype, 0)
>         uploaded_file.save(rst.path)
>         with open(rst.path, 'rb') as f:
>             filemd5 = get_file_md5(f)
>             uploaded_file = cls.get_by_md5(filemd5)
>             if uploaded_file:
>                 os.remove(rst.path)
>                 return uploaded_file
>         filestat = os.stat(rst.path)
>         rst.size = filestat.st_size
>         rst.filemd5 = filemd5
>         return rst**

> 
> 改为：
> 
**>  def create_by_upload_file(cls, uploaded_file):
>         rst = cls(uploaded_file.filename, uploaded_file.mimetype, 0)
>         uploaded_file.save(rst.path)
>         with open(rst.path, 'rb') as f:
>             filemd5 = get_file_md5(f)
>             uploaded_file = cls.get_by_md5(filemd5)
>         if uploaded_file:
>             os.remove(rst.path)
>             return uploaded_file
>         filestat = os.stat(rst.path)
>         rst.size = filestat.st_size
>         rst.filemd5 = filemd5
>         return rst**
> 
 删除文件时

需要关闭进程对文件的引用，因此需要调整下缩进，把删除的代码放在with语句的外面。

另：修改后发现，多次上传同一个文件（文件名相同）目录里仍然存在“同个”文件，只是文件名不同，没有达到只存储同一文件的效果，请作者查看下这个问题

**Comment by CheungChan** [comment]
为啥我的没有报错呢，文件改名了也没有新增文件。你看看是不是哪里搞错了

**Comment by dongweiming** [comment]
@ShoneKey 你的书是第一或者第二版么？第三版的时候改过一点内容，具体的你可以参看 https://github.com/dongweiming/web_develop/blob/master/errata.md 。不过我刚才试了下是正常的呀。你pull最新的代码试试？
