### ISSUE TITLE
vagrant ssh连的虚拟机在宿主机浏览器上无法访问

### ISSUE THREAD

**Issue by CheungChan** [dongweiming/web_develop#57]
如题，无论是8000端口，9000端口还是3414端口，虚拟机中起了http服务，宿主机浏览器均无法访问。能ping通ip，但是telnet加端口号也无法建立连接。

**Comment by CheungChan** [comment]
自己解决了，原来不能用虚拟机的ip，用127.0.0.1就能访问

**Comment by akayj** [comment]
可以有2种办法:

1. NAT: ip可以用 **127.0.0.1**, port看你转发出来的端口
e.g:
`config.vm.network "forwarded_port", guest: 80, host: 8080`
访问: `http://localhost:8080/`
2. Private Network: ip是新的私有网段的ip， port则是虚拟机内部监听的端口。
例:
` config.vm.network "private_network", ip: "192.168.33.10"`
访问: `http://192.168.33.10/`
