### ISSUE TITLE
Docker image can't pull down,作者能否将docker镜像分享出来呀?

### ISSUE THREAD

**Issue by LightlyFly** [dongweiming/web_develop#58]
错误信息:
Error response from daemon: Get https://registry-1.docker.io/v2/dongweiming/web_develop/manifests/dev: Get https://auth.docker.io/token?scope=repository%3Adongweiming%2Fweb_develop%3Apull&service=registry.docker.io: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
作者能否将镜像分享出来呀

**Comment by dongweiming** [comment]
试试国内的镜像吧，https://www.zhihu.com/question/55135855
