### ISSUE TITLE
第14章 431页， 关于OrderedDict 有歧义

### ISSUE THREAD

**Issue by xkoma007** [dongweiming/web_develop#59]
OrderedDict是一个根据键值（keys）插入顺序排序的词典，
例子:
d = collections.OrderedDict([('a', 1), ('c', 2), ('b', 3)])
for k, v in d.items():
    print(k, v)

书中误以为该词典是根据键值（keys）作排序的

**Comment by dongweiming** [comment]
@beyondkoma 我书里面写的是「可以使用OrderedDict这个数据结构来保证字典键值对的顺序」，这话没有错啊，我并没有说是根据键值做排序？

**Comment by xkoma007** [comment]
好吧， 可能是个人习惯理解问题~~
