### ISSUE TITLE
git文件目录的组织不太合理

### ISSUE THREAD

**Issue by ghost** [dongweiming/web_develop#60]
一边看书，一边根据书上的内容看下git。但是发现一个问题，就是无法根据所看的章节快速定位到该章节代码存放于哪个目录，而且代码里面代码文件与模板文件也是分开的，找到代码还得再找到模板。例如81页的例子文件服务器，根据章节找到chapter3，但是无法判断出属于哪个section，找到section5后，再去templates目录下去找模板文件，但是模板文件又不在section3里，竟然在 r 目录下，这样文件找起来很费劲。为什么不在书上每个例子后面指明源码所在目录，然后在该目录下放置所有的文件，这样一目了然，而且还可以直接试运行。

**Comment by dongweiming** [comment]
@Green-unicorn 当时考虑过狗书的方式: 不同的章节使用不同的Tag。最后没有使用这个方案的原因是狗书原来是一个系列的博客文章，发布很久之后编辑成书，内容是之前就有的。而我这本是从无到有，非常有可能后期要不断的重构。

我在前言的「使用代码示例」中提到如何使用：

> 例子文件的名字在书的对应位置会提到，文件存放在对应的章节的子目录下，比如第3章第1节的例子，就会放在chapter3/section1目录下。有一些文件是相对于项目根目录的，比如静态文件统一存放在static目录下，模板文件统一存放在templates目录下。绝大多数模板文件使用相同的对应章节的约定，比如第4章第2节的模板存放在templates/chapter4/section2目录下。

等你习惯这样的约定就好了。你说的 r 这个问题应该是当时重构时候忽略了，抱歉啦
