### ISSUE TITLE
第九章 Celery部分 代码问题

### ISSUE THREAD

**Issue by gutou901** [dongweiming/web_develop#61]
celeryconfig.py中
BROKER_URL填写的是amqp://xxxxx
这样填启动后发现在会报Received and deleted unknown message.  Wrong destination?!?的错误..
将BROKER_URL改成pyamqp://xxxxx以后问题解决...

排查了下发现应该是按照P265 (安装配置Celery) 中的命令安装了librabbitmq导致的..

如果还想使用amqp 就必须要执行pip uninstall librabbitmq才可以...

不知道这算不算是一个错误...

**Comment by dongweiming** [comment]
@gutou901 你看下 https://github.com/dongweiming/web_develop/issues/48 可不可以帮你解决掉？
