### ISSUE TITLE
关于表单验证

### ISSUE THREAD

**Issue by ghost** [dongweiming/web_develop#62]
在本书中，我看到只有在102提到了wtforms的表单验证，但是wtfoms的表单验证属于前后一体式的结构，无法用于前后分离的结构中，验证后的错误信息无法返回给前端，如果前端采用ajax提交的话，就会有问题。或者说在API中也无法使用，请问在这种情况下，应该采用何种方法在后端做表单验证呢？如果是要自己写的话，能否提供一个样例daemon供学习……

**Comment by dongweiming** [comment]
我在日常工作中不怎么用wtforms这种页面提交的方式修改数据，因为我觉得处理起来业务越复杂逻辑处理起来就越麻烦，而且不灵活。通常都是用前后端分离的方式，利用react/vue请求api的方式实现数据的交互。

不过wtforms配合jQuery之类的框架写javascript程序对数据进行处理也是可以验证的。这种例子网上也是有的，实现原理大同小异，不过前后端都要进行表单验证，防止利用漏洞直接ajax提交给后端
