### ISSUE TITLE
小错误

### ISSUE THREAD

**Issue by logchi** [dongweiming/web_develop#63]
Chapter3 P38, 响应 (尾部)

转换为一个请求对象 --> 转换为一个响应对象

**Comment by pyxin** [comment]
第二章 19页
.strip()  返回的是一个list 要取一下[0]

顺便问下 怎么定制化3.5  我改了版本还是不行 提示找不到pip

**Comment by dongweiming** [comment]
@logchi 感谢，之前一直手上没有书

**Comment by dongweiming** [comment]
@pyxin 你说的strip是list 具体是哪里呢？

**Comment by pyxin** [comment]
好早的 当初不懂....
