### ISSUE TITLE
第九章 Celery 关于定时任务的问题

### ISSUE THREAD

**Issue by Caratpine** [dongweiming/web_develop#64]
书中270页

> Beat 和 Worker 进程可以一并启动：
>  \>celery -B -A -projb worker -l info

Celery 的[文档](http://docs.celeryproject.org/en/3.1/reference/celery.bin.worker.html#cmdoption-celery-worker-b)里面标注：
> Also run the celery beat periodic task scheduler. Please note that there must only be one instance of this service.

用书中的描述的方式启动 Celery 会有多个进程。

这个问题希望能在再版书中说明清楚:-)

**Comment by yangyang-zhang** [comment]
我现在按照书中celery  beat -A projb启动服务，服务也都正常，但是并没有看到定时任务每10秒执行一次，不知道什么原因，这个是添加的参数
```
CELERYBEAT_SCHEDULE = {
    'add':{
        'task': 'projectb.tasks.add',
        'schedule': timedelta(seconds=10),
        'args': (16, 16)
    }
}

```

执行Beat程序
```
yangyang@yangyang-VirtualBox:~$ celery beat -A projectb
celery beat v4.1.0 (latentcall) is starting.
__    -    ... __   -        _
LocalTime -> 2017-11-21 11:00:25
Configuration ->
    . broker -> amqp://guest:**@localhost:5672//
    . loader -> celery.loaders.app.AppLoader
    . scheduler -> celery.beat.PersistentScheduler
    . db -> celerybeat-schedule
    . logfile -> [stderr]@%WARNING
    . maxinterval -> 5.00 minutes (300s)

```

执行worker进程

```
yangyang@yangyang-VirtualBox:~$ celery -A projectb worker -l info
 
 -------------- celery@yangyang-VirtualBox v4.1.0 (latentcall)
---- **** ----- 
--- * ***  * -- Linux-4.4.0-92-generic-x86_64-with-Ubuntu-16.04-xenial 2017-11-21 11:01:34
-- * - **** --- 
- ** ---------- [config]
- ** ---------- .> app:         project:0x7fb8abc53190
- ** ---------- .> transport:   amqp://guest:**@localhost:5672//
- ** ---------- .> results:     redis://localhost:6379/0
- *** --- * --- .> concurrency: 2 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . project.tasks.add

[2017-11-21 11:01:34,528: INFO/MainProcess] Connected to amqp://guest:**@localhost:5672//
[2017-11-21 11:01:34,576: INFO/MainProcess] mingle: searching for neighbors
[2017-11-21 11:01:35,647: INFO/MainProcess] mingle: all alone
[2017-11-21 11:01:35,729: INFO/MainProcess] celery@yangyang-VirtualBox ready.
```

**Comment by Caratpine** [comment]
@yangyang-zhang 
可否贴一下你的代码？
从你上面给的信息
你的`CELERY BEAT_SCHEDULE`的 task 是 `projectb.tasks.add`
而你的 celery worker 当中 task 是`project.tasks.add`

**Comment by yangyang-zhang** [comment]
谢谢你的提醒，我才发现，我直接copy另外的代码，实例化的时候，include这个项目名称没有修改，但是我现在更改过后，重新运行，已经可以了。

**Comment by Caratpine** [comment]
@yangyang-zhang 👌

**Comment by dongweiming** [comment]
> Celery 的文档里面标注：

> Also run the celery beat periodic task scheduler. Please note that there must only be one instance of this service.
> 用书中的描述的方式启动 Celery 会有多个进程。

文档的意思是「产生任务的」beat进程只能有一个。`celery -B -A -projb worker -l info`这种方式worker+beat一起启动肯定是多个进程

**Comment by dongweiming** [comment]
也感谢 @Caratpine

**Comment by Caratpine** [comment]
@dongweiming 

我在生产环境中用到了书中`celery -B -A -projb worker -l info`方式启动了我的 celery 服务，但是突然有一天定时任务莫名其妙的不按照配置当中的时间点执行任务，时不时就执行一次。

我看了文档之后单独运行了 beat 进程，解决了这个问题，所以我觉得`celery -B -A -projb worker -l info`这种方式启动存在 BUG 不应该提倡，希望在再版的书中能够说明一下。

**Comment by dongweiming** [comment]
我不觉得celery会出现这种bug，如果确实是 你应该给celery提issue描述这件事，而不是让我弃用这种方式 @Caratpine

**Comment by Caratpine** [comment]
@dongweiming 
好的 thanks👌
