### ISSUE TITLE
基于Windows的docker环境，本书的内容是否可用呢？@dongweiming

### ISSUE THREAD

**Issue by sanweiChang** [dongweiming/web_develop#66]

**Comment by sanweiChang** [comment]
我是安装的Windows下的docker环境，把书中的docker环境docker pull 下来之后，进入的是/home/ubuntu/web_develop目录，试了一下，pip命令不能用，ifconfig命令，不能用，git pull代码也pull不下来，怎么解决呢？

**Comment by dongweiming** [comment]
@sanweiChang 额，windows下用docker我没有经验。你是用的 Windows Subsystem for Linux (WSL)  么？ 我还是建议你使用Linux的系统
