### ISSUE TITLE
勘误 

### ISSUE THREAD

**Issue by tntC4stl3** [dongweiming/web_develop#7]
第二章 P17 第一行，应为 `安装 pep8-naming`。

**Comment by tntC4stl3** [comment]
第三章 P31 最后一行：
既然设置的环境变量是 `YOURAPPLICATION_SETTINGS`，那么加载的时候也必须通过 `app.config.from_envvar('YOURAPPLICATION_SETTINGS')`加载。

**Comment by dongweiming** [comment]
感谢 已改正 https://github.com/dongweiming/web_develop/commit/a757c02a0817c6107a2a899632bd3bd8c49755c2

**Comment by dongweiming** [comment]
@tntC4stl3 请问你在北京么？如果在并且想去pycon北京场，我可以送你票作为勘误的感谢 😄
