### ISSUE TITLE
nginx 配置检查失败

### ISSUE THREAD

**Issue by Kevin-Zhang225** [dongweiming/web_develop#73]
nginx 的默认配置已经按照书中的指示替换为 nginx_gunicoren.conf 。可是`sudo /etc/init.d/nginx configtest`时出错，信息如下：
![image](https://user-images.githubusercontent.com/15984258/44223967-bdcbb380-a1bb-11e8-90ad-c7cfc4095a87.png)

有什么建议么？谢谢啦

**Comment by Kevin-Zhang225** [comment]
已经解决。方法如下：
1. 使用 `sudo nginx -t` 定位到 配置文件的第一行有错。第一行内容为：`user  ubuntu ubuntu;`
2. 将 第一行配置改为：`user root root;`
3. 配置文件检查成功

ps: 呼吁小明常来逛逛哈

**Comment by dongweiming** [comment]
@MarinZhang 抱歉哈，忘了关注了.. 看不到你的报错图片了

但我墙裂不建议使用root启动nginx！

**Comment by dongweiming** [comment]
能发一下详细的错误嘛？我平时线上环境都是这么用，也没有问题...
