### ISSUE TITLE
 The box 'dongweiming/web_develop' could not be found.

### ISSUE THREAD

**Issue by sundaygeek** [dongweiming/web_develop#74]
![Uploading image.png…]()

**Comment by sundaygeek** [comment]
Bringing machine 'default' up with 'virtualbox' provider...
There are errors in the configuration of this machine. Please fix
the following errors and try again:

SSH:
* The following settings shouldn't exist: insert_key, password

vm:
* The box 'dongweiming/web_develop' could not be found.

**Comment by dongweiming** [comment]
我明天看一下，你可以使用 https://github.com/dongweiming/web_develop#%E9%87%8D%E8%A6%81%E6%8F%90%E7%A4%BA 提到的[百度网盘](https://pan.baidu.com/s/1mhQmCac)下载box文件，做本地安装

**Comment by dongweiming** [comment]
<img width="1440" alt="屏幕快照 2019-04-26 上午7 46 08" src="https://user-images.githubusercontent.com/841395/56774949-69bba900-67f7-11e9-937f-b33a038baf07.png">

@sundaygeek 我试了下有呀
