### ISSUE TITLE
/chapter4/section3/hashed_user.py中＠hybrid_property的setter错误

### ISSUE THREAD

**Issue by for-in** [dongweiming/web_develop#75]
@hybrid_property
    def password(self):
　     return self._password 
　@password.setter
    def _set_password(self, plaintext):
　　self._password = generate_password_hash(plaintext)
这段代码的函数名_set_password貌似需要改成password?

**Comment by dongweiming** [comment]
@for-in 啊 确实是，通常的习惯是直接setter包装的函数用同名。不知道当时写书的时候为什么这段可以跑过了。感谢反馈
