### ISSUE TITLE
modified:   chapter14/section4/hello

### ISSUE THREAD

**Issue by handsomeWeiye** [dongweiming/web_develop#77]
想要更新代码
λ git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   chapter14/section4/hello

no changes added to commit (use "git add" and/or "git commit -a")

**Comment by dongweiming** [comment]
@handsomeWeiye 没看懂，你修改文件了？

你可以`git reset --hard`放弃全部提交再用`git pull --rebase`更新
