### ISSUE TITLE
第3章 P58 mako模板继承

### ISSUE THREAD

**Issue by MrCJJW** [dongweiming/web_develop#8]
```
<!DOCTYPE html>
<html lang="en">
<head>
    <%block name="head">
        <meta charset="UTF-8">
        <title>${ title() } - My Webpage</title>
    </%block>
</head>
<body>
    <div id="content">
        <%block name="content"/>
    </div>
    <div id="footer">
        <%block name="footer"/>
    </div>
</body>
</html>

<%def _name='title()'></%def>
```

`<title>${ title() } - My Webpage</title>`
是否改为
`<title>${ self.title() } - My Webpage</title>`。
如果没加self，子模板继承后就算重写title()函数，使用parernt.head()时使用的还是原来的title函数，但此处例子是希望子模板改写title函数使相关内容发生改变

**Comment by dongweiming** [comment]
@MrCJJW 是的。是我的写的考虑不周了，再版的时候会改正这个地方的

**Comment by dongweiming** [comment]
@MrCJJW 已改正 https://github.com/dongweiming/web_develop/commit/f9a6b608207dcf23c2241f1ed1997ae5ecd12a11 感谢反馈
